spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/LinoleumShopRestDatabase
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        hbm2ddl.auto: update
        javax.cache:
           provider: org.ehcache.jsr107.EhcacheCachingProvider
           uri: classpath:ehcache.xml
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    open-in-view: false
server:
  port: 8080
  error:
    include-message: always
logging:
  file:
    path: ../logs
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 15MB

